force-app/main/default/objects/Movie__c/Movie__c.object-meta.xml
<CustomObject>
    <label>Movie</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Movies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Movie__c/fields/IsReleased__c.field-meta.xml
<CustomField>
    <fullName>IsReleased__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Released</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Movie__c/fields/ReleaseDate__c.field-meta.xml
<CustomField>
    <fullName>ReleaseDate__c</fullName>
    <label>Release Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/UpdateReleasedMoviesBatch.cls
public with sharing class UpdateReleasedMoviesBatch implements Database.Batchable<sObject>{
    public Database.QueryLocator start(Database.BatchableContext BC)
    {
        String query = 'SELECT Id,IsReleased__c,ReleaseDate__c '+
                       'FROM Movie__c '+
                       'WHERE ReleaseDate__c <= TODAY '+
                       'AND isReleased__c != true';
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext BC, List<Movie__c> movies)
    {
        List<Movie__c> moviesToUpdate = new List<Movie__c>();
        for(Movie__c movie : movies)
        {
            movie.isReleased__c = true;
            moviesToUpdate.add(movie);
        }
        update moviesToUpdate;
    }
   
    public void finish(Database.BatchableContext BC) {
         
    }
}