force-app/main/default/objects/Actor__c/Actor__c.object-meta.xml
<CustomObject>
   
    <label>Actor</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Actors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Movie__c/Movie__c.object-meta.xml
<CustomObject>
    <label>Movie</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Movies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Movie__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Action</fullName>
            </value>
            <value>
                <fullName>Adventure</fullName>
            </value>
            <value>
                <fullName>Comedy</fullName>
            </value>
            <value>
                <fullName>Drama</fullName>
            </value>
            <value>
                <fullName>Horror</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Movie__c/fields/ReleaseDate__c.field-meta.xml
<CustomField>
    <fullName>ReleaseDate__c</fullName>
    <label>Release Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/MovieActor__c/MovieActor__c.object-meta.xml
<CustomObject>
    <label>Movie Actor</label>
    <nameField>
        <label>Movie Actor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Movies Actors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MovieActor__c/fields/Actor__c.field-meta.xml
<CustomField>
    <fullName>Actor__c</fullName>
    <label>Actor</label>
    <referenceTo>Actor__c</referenceTo>
    <relationshipLabel>Movies Actors</relationshipLabel>
    <relationshipName>Movies_Actors</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MovieActor__c/fields/Movie__c.field-meta.xml
<CustomField>
    <fullName>Movie__c</fullName>
    <label>Movie</label>
    <referenceTo>Movie__c</referenceTo>
    <relationshipLabel>Movies Actors</relationshipLabel>
    <relationshipName>Movies_Actors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/moviesController.cls
public with sharing class moviesController {


    @AuraEnabled(cacheable=true)
    public static List<Movie__c> getMovies(String movieName){

        List<Movie__c> moviesList = new List<Movie__c>();
        if(!String.isBlank(movieName)){
            String nm = '%' + movieName + '%';
            moviesList = [SELECT Id, Name, Description__c, Category__c, ReleaseDate__c, Image__c
                                        FROM Movie__c WHERE Name like: nm];

        }else if(String.isBlank(movieName)){
            moviesList = [SELECT Id, Name, Description__c, Category__c, ReleaseDate__c, Image__c
                                        FROM Movie__c];
        }

        return moviesList;
    }
    @AuraEnabled(Cacheable=false)
    public static void createMovie(NewMovie movie, List<String> actorsIds){

        Movie__c newMovieToinsert = new Movie__c();

        newMovieToinsert.Name = movie.name;
        newMovieToinsert.Category__c = movie.category;
        newMovieToinsert.Description__c = movie.description;
        newMovieToinsert.ReleaseDate__c = movie.releaseDate;
    
        insert newMovieToinsert;
    
        List<MovieActor__c> movieActorsToinsert  = new List<MovieActor__c>();

        Map<Id, Actor__c> actors = new Map<Id,Actor__c>([SELECT Id, Name FROM Actor__c WHERE Id IN: actorsIds]);

        for(String actorId : actorsIds){

            MovieActor__c movieActor = new MovieActor__c();

            movieActor.name = newMovieToinsert.Name + '_' + actors.get(actorId).Name;
            movieActor.Actor__c = actorId;
            movieActor.Movie__c = newMovieToinsert.Id;
            movieActorsToinsert.add(movieActor);
        }


        insert movieActorsToinsert;
    }

    public class NewMovie{

        @AuraEnabled
        public String name {get; set;}

        @AuraEnabled
        public String description {get; set;}

        @AuraEnabled
        public String category {get; set;}

        @AuraEnabled
        public Date releaseDate {get; set;}

      
    }

}