force-app/main/default/objects/Actor__c/Actor__c.object-meta.xml
<CustomObject>
   
    <label>Actor</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Actors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Actor__c/fields/NumberOfMovies__c.field-meta.xml
<CustomField>
    <fullName>NumberOfMovies__c</fullName>
    <label>Number of movies</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Movie__c/Movie__c.object-meta.xml
<CustomObject>
    <label>Movie</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Movies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Movie__c/fields/FemaleActorsPercentage__c.field-meta.xml
<CustomField>
    <fullName>FemaleActorsPercentage__c</fullName>
    <label>Female Actors Percentage</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Movie__c/fields/MaleActorsPercentage__c.field-meta.xml
<CustomField>
    <fullName>MaleActorsPercentage__c</fullName>
    <label>Male Actors Percentage</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/MovieActor__c/MovieActor__c.object-meta.xml
<CustomObject>
    <label>Movie Actor</label>
    <nameField>
        <label>Movie Actor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Movies Actors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MovieActor__c/fields/Actor__c.field-meta.xml
<CustomField>
    <fullName>Actor__c</fullName>
    <label>Actor</label>
    <referenceTo>Actor__c</referenceTo>
    <relationshipLabel>Movies Actors</relationshipLabel>
    <relationshipName>Movies_Actors</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MovieActor__c/fields/Movie__c.field-meta.xml
<CustomField>
    <fullName>Movie__c</fullName>
    <label>Movie</label>
    <referenceTo>Movie__c</referenceTo>
    <relationshipLabel>Movies Actors</relationshipLabel>
    <relationshipName>Movies_Actors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/MovieActorTriggerHandler.cls
public with sharing class MovieActorTriggerHandler {

    public void AdjustMovieNumberAndGenderPercentage(List<MovieActor__c> movieActorList){

        String FEMALE_GENDER = 'Female';
        String MALE_GENDER   = 'Male';

        List<Movie__c> moviesToUpdate = new List<Movie__c>();
        List<String> actorsIds = new List<String>();
        List<String> moviesIds = new List<String>();

        for(MovieActor__c ma : movieActorList){
            actorsIds.add(ma.Actor__c);
            moviesIds.add(ma.Movie__c);
        }

        Map<Id, Actor__c> actorsMap = new Map<Id, Actor__c>([SELECT Id, NumberOfMovies__c, Gender__c 
                                                                FROM Actor__c 
                                                                WHERE Id IN: actorsIds]);

        for(Actor__c actor : actorsMap.values()){
            actor.NumberOfMovies__c += 1;
        }
        update actorsMap.values();

        List<MovieActor__c> allMovies = [SELECT Id, Actor__c, Movie__c
                                            FROM MovieActor__c 
                                            WHERE Movie__c IN: moviesIds
                                            ];

        Map<Id, List<Integer>> numberActorsPerMovie = new Map<Id, List<Integer>>();

        for(MovieActor__c m : allMovies){

            if(numberActorsPerMovie.containsKey(m.Movie__c)){
                numberActorsPerMovie.get(m.Movie__c)[0] = numberActorsPerMovie.get(m.Movie__c)[0]+1;
            } 
            else{
                numberActorsPerMovie.put(m.Movie__c, new List<Integer>{1,0,0});            
            }

            if(actorsMap.get(m.Actor__c).Gender__c == FEMALE_GENDER){
                numberActorsPerMovie.get(m.Movie__c)[1] = numberActorsPerMovie.get(m.Movie__c)[1]+1;
            }
            else if(actorsMap.get(m.Actor__c).Gender__c == MALE_GENDER){
                numberActorsPerMovie.get(m.Movie__c)[2] = numberActorsPerMovie.get(m.Movie__c)[2]+1;
            }

        }

        for(Id movieId : numberActorsPerMovie.keySet()){

            Movie__c movieToUpdate = new Movie__c();
            movieToUpdate.Id = movieId;
            movieToUpdate.FemaleActorsPercentage__c = (numberActorsPerMovie.get(movieId)[1] * 100)/numberActorsPerMovie.get(movieId)[0];
            movieToUpdate.MaleActorsPercentage__c   = (numberActorsPerMovie.get(movieId)[2] * 100)/numberActorsPerMovie.get(movieId)[0];
            moviesToUpdate.add(movieToUpdate);

        }

        update moviesToUpdate;
        
    }

}